config/routes.rb
class ChannelConstraint
  def matches?(request)
    subdomain = Channelable.subdomain(request)
    subdomain.present? && subdomain != "www"
  end
end

class NoChannelConstraint
  def matches?(request)
    !ChannelConstraint.new.matches?(request)
  end
end

Rails.application.routes.draw do
  match "/auth/:provider/callback", to: "sessions#create", via: %i[get post]
  resource :session

  constraints(ChannelConstraint.new) do
    root to: "channels#show", as: :channel_root

    resource :channel
    resources :streams
  end

  constraints(NoChannelConstraint.new) do
    root to: "pages#home"
  end
end

app/models/twitch/channel.rb
module Twitch
  class Channel < ApplicationRecord
    has_many :streams, foreign_key: :twitch_channel_id

    delegate :to_param, to: :username
    delegate :to_s, to: :display_name
  end
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  after_action :verify_authorized
  after_action :verify_policy_scoped, only: :index

  include Channelable

  layout "channel"

  rescue_from Channelable::NoChannelError do |_exception|
    @channel = Twitch::Channel.new(username: subdomain)

    if policy(@channel).create?
      render :new, layout: "application"
    else
      render :missing, status: 404, layout: "application"
    end
  end

  def show
    @stream = authorize(twitch_channel).streams.active.first

    return unless @stream

    render "streams/show"
  end

  def create
    if twitch_channel?
      authorize(twitch_channel)
      redirect_to root_url and return
    end

    user = Twitch::User.find_by(login: subdomain)

    channel = Twitch::Channel.new(username: subdomain, display_name: user&.display_name || subdomain)

    authorize(channel)

    channel.save
    redirect_to root_url
  end

  def edit
    authorize(twitch_channel)
  end

  def update
    authorize(twitch_channel).update(channel_params)

    redirect_to channel_url
  end

  def destroy
    authorize(twitch_channel).destroy

    redirect_to root_url
  end

  private

  def channel_params
    params.require(:channel).permit(:sync_moderators)
  end
end

app/views/channels/edit.html.haml
%h1 Edit channel #{twitch_channel}

= form_for twitch_channel do |f|

  .field
    %label
      = f.check_box :sync_moderators
      Sync moderators

  = f.submit

app/views/channels/missing.html.haml
%h1 This channel doesn't exist

app/views/channels/new.html.haml
%h1 Create this channel

= form_for(@channel, url: channel_path) do |f|

  = f.submit

-# TODO: Actual channel creation

app/views/channels/show.html.haml
%h1 Channel #{twitch_channel}!

- if policy(twitch_channel).create?
  = link_to "Edit channel", edit_channel_url

- if policy(twitch_channel).destroy?
  = button_to "Unlink channel", channel_url, method: :delete

%p no active stream