config/routes.rb
class ChannelConstraint
  def matches?(request)
    subdomain = Channelable.subdomain(request)
    subdomain.present? && subdomain != "www"
  end
end

class NoChannelConstraint
  def matches?(request)
    !ChannelConstraint.new.matches?(request)
  end
end

Rails.application.routes.draw do
  match "/auth/:provider/callback", to: "sessions#create", via: %i[get post]
  resource :session

  constraints(ChannelConstraint.new) do
    root to: "channels#show", as: :channel_root

    resource :channel
    resources :streams
  end

  constraints(NoChannelConstraint.new) do
    root to: "pages#home"
  end
end

app/models/stream.rb
class Stream < ApplicationRecord
  belongs_to :twitch_channel, class_name: "Twitch::Channel"

  validates :title, presence: true

  scope :active_at,
        lambda { |ts|
          where("starts_at < ?", ts).where("extract(epoch from (? - starts_at)) < initial_duration", ts)
        }

  scope :active, -> { active_at(Time.now) }
end

app/controllers/streams_controller.rb
class StreamsController < ApplicationController
  include Channelable

  before_action :set_stream, only: %i[show edit update destroy]
  after_action :verify_authorized
  after_action :verify_policy_scoped, only: :index

  # GET /streams or /streams.json
  def index
    @streams = authorize policy_scope(twitch_channel.streams)
  end

  # GET /streams/1 or /streams/1.json
  def show; end

  # GET /streams/new
  def new
    @stream = authorize twitch_channel.streams.build
  end

  # GET /streams/1/edit
  def edit; end

  # POST /streams or /streams.json
  def create
    @stream = authorize twitch_channel.streams.build(stream_params)

    respond_to do |format|
      if @stream.save
        format.html { redirect_to stream_url(@stream), notice: "Stream was successfully created." }
        format.json { render :show, status: :created, location: @stream }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stream.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /streams/1 or /streams/1.json
  def update
    respond_to do |format|
      if @stream.update(stream_params)
        format.html { redirect_to stream_url(@stream), notice: "Stream was successfully updated." }
        format.json { render :show, status: :ok, location: @stream }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stream.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /streams/1 or /streams/1.json
  def destroy
    @stream.destroy

    respond_to do |format|
      format.html { redirect_to streams_url, notice: "Stream was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_stream
    @stream = authorize twitch_channel.streams.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def stream_params
    params.require(:stream).permit(:title, :starts_at, :initial_duration)
  end
end

app/helpers/streams_helper.rb
module StreamsHelper
end

app/views/streams/_form.html.haml
= form_with(model: stream) do |form|
  - if stream.errors.any?
    %div{style: "color: red"}
      %h2
        = pluralize(stream.errors.count, "error")
        prohibited this stream from being saved:
      %ul
        - stream.errors.each do |error|
          %li= error.full_message
  %div
    = form.label :title, style: "display: block"
    = form.text_field :title
  %div
    = form.label :starts_at, style: "display: block"
    = form.datetime_field :starts_at
  %div
    = form.label :initial_duration, style: "display: block"
    = form.number_field :initial_duration
  %div
    = form.submit

app/views/streams/_stream.html.haml
%div{id: "#{dom_id stream}"}
  %p
    %strong Title:
    = stream.title
  %p
    %strong Starts at:
    = stream.starts_at
  %p
    %strong Initial duration:
    = stream.initial_duration

app/views/streams/edit.html.haml
%h1 Editing stream
= render "form", stream: @stream
%br/
%div
  = link_to "Show this stream", @stream
  |
  \#{link_to "Back to streams", streams_path}

app/views/streams/index.html.haml
%p{style: "color: green"}= notice
%h1 Streams
#streams
  - @streams.each do |stream|
    = render stream
    %p
      = link_to "Show this stream", stream
- if policy(Stream).new?
  = link_to "New stream", new_stream_path

app/views/streams/new.html.haml
%h1 New stream
= render "form", stream: @stream
%br/
%div
  = link_to "Back to streams", streams_path

app/views/streams/show.html.haml
%p{style: "color: green"}= notice
= render @stream
%div
  - if policy(@stream).edit?
    = link_to "Edit this stream", edit_stream_path(@stream)
  - if policy(@stream).index?
    = link_to "Back to streams", streams_path
  - if policy(@stream).destroy?
    = button_to "Destroy this stream", @stream, method: :delete